combined remote and local into one

diff --git a/lazyproject-create b/lazyproject-create
--- a/lazyproject-create
+++ b/lazyproject-create
@@ -10,20 +10,328 @@
 		exit 1
 	fi
 
-	./lazyproject-create-remote $1
-	./lazyproject-create-local $1
+	MSG_INSTALL_ABORTED="Installation aborted."
 
-	echo -e "=== Opening site in the default browser ... \n"
+	server=minerva
+	defaultpass=LelEMa1e
+	site_db=$1		# Name of the MySQL wordpress database
+	site_db_user=$1	# Database user account
+	cwd=${PWD#*/}
+
+	# Check that wp-cli is installed
+	hash wp &> /dev/null
+	if [ $? -eq 1 ]; then
+		echo >&2 "=== ERROR: wp-cli is required. Check http://wp-cli.org for more information."
+		echo -e "\n=== Just execute the following command in your terminal: \n"
+		echo -e "    curl https://raw.github.com/wp-cli/wp-cli.github.com/master/installer.sh | bash \n"
+		echo -e "    (Make sure to read the instructions) \n"
+		echo -e "=== ${MSG_INSTALL_ABORTED} ===================================================== \n"
+		exit 1
+	fi
+
+	# Check that the MySQL server us running
+	UP=$(pgrep mysql | wc -l);
+	if [ "$UP" -ne 1 ];
+	then
+		echo -e "=== ERROR: MySQL not running!\n"
+		echo -e "=== This script needs MySQL running in order to install and configure"
+		echo -e "=== the WordPress database. \n"
+		echo -e "=== ${MSG_INSTALL_ABORTED} ===================================================== \n"
+		exit 1
+	fi
+
+	# Check that the Database the script is about to create doesn't exist
+	if [ -d $MYSQL_DATA_DIR$site_db ]
+	then
+		echo -e "=== ERROR: Database '$site_db' aready exists! \n"
+		echo -e "=== ${MSG_INSTALL_ABORTED} ===================================================== \n"
+		exit 1
+	fi
+
+	# Does the new VHost directory already exists?
+	if [ -d "$APACHE_VHOSTS_ROOT_DIR$1" ] 
+	then 
+		echo -e '=== ERROR: Site directory already exists! Cannot create new VHost. \n'
+		echo -e "=== ${MSG_INSTALL_ABORTED} ===================================================== \n"
+		exit 1
+	fi
+
+	{
+		cat ~/.ssh/id_rsa.pub 
+	} > authorized_keys
+
+	{ 	
+		echo '<VirtualHost *:80>'
+		echo '	DocumentRoot "'/home/$1/site/htdocs'"'
+		echo "	ServerName ($1).test.rhyndo.com"
+		echo '	SetEnv APPLICATION_ENV staging'
+		echo '	<Directory '/home/$1/site/htdocs'>'
+		echo '		Options FollowSymLinks'
+		echo '		AllowOverride All'
+		echo '		Order deny,allow'
+		echo '		Allow from all'
+		echo '	</Directory>'
+		echo '</VirtualHost>'
+	} > $1.conf
+
+	# User creation & Authentication setup
+	ssh root@$server "useradd -m $1 && echo -e '$defaultpass\n$defaultpass' | passwd $1" > /dev/null 2>&1
+	echo -e "=== User $1 created on server: $server"
+	
+	sshpass -p $defaultpass ssh $1@$server "mkdir -p .ssh" > /dev/null 2>&1
+	sshpass -p $defaultpass scp authorized_keys $1@$server:.ssh > /dev/null 2>&1
+	sshpass -p $defaultpass ssh $1@$server "chmod go-w .ssh && chmod 600 .ssh/authorized_keys"
+	echo -e "=== SSH Keys authentication config finished"
+
+	ssh $1@$server "mkdir repo && mkdir site && cd repo && mkdir $1.git && cd $1.git && git init --bare"  > /dev/null 2>&1
+	
+	{
+		echo "#!/bin/sh"
+		echo "git --work-tree=/home/$1/site --git-dir=/home/$1/repo/$1.git checkout -f"
+	} > post-receive
+
+	scp post-receive $1@$server:repo/$1.git/hooks  > /dev/null 2>&1
+	ssh $1@$server "cd repo/$1.git/hooks && chmod +x post-receive"
+	echo -e "=== Git repo config finished"
+
+	# Cleaning up ...
+	#rm $1.conf
+	rm post-receive
+	rm authorized_keys
+
+	echo -e "=== Remote setup - finished \n"
+
+	# Local installation starts
+	mkdir $APACHE_VHOSTS_ROOT_DIR$1
+	cd $APACHE_VHOSTS_ROOT_DIR$1
+	
+	mkdir htdocs
+	mkdir htdocs/wordpress
+	mkdir config
+	mkdir config/env
+	mkdir scripts
+	mkdir database
+
+	{ 	
+		echo '<VirtualHost *:80>'
+		echo '	DocumentRoot "'$APACHE_VHOSTS_ROOT_DIR$1/htdocs'"'
+		echo '	ServerName '$1
+		echo '	SetEnv APPLICATION_ENV development'
+		echo '	<Directory '$APACHE_VHOSTS_ROOT_DIR$1/htdocs'>'
+		echo '		Options FollowSymLinks'
+		echo '		AllowOverride All'
+		echo '		Order deny,allow'
+		echo '		Allow from all'
+		echo '	</Directory>'
+		echo '</VirtualHost>'
+	} > /Users/koko/Sites/_vhosts/$1.conf
+
+	echo -e "=== VHost file created"
+
+	# Add the site to the local hosts file
+	sudo sh -c "echo '127.0.0.1	'$1 >> $HOSTS_FILE"
+	echo -e "=== hosts file updated"
+
+	sudo apachectl -k stop > /dev/null 2>&1
+	sudo apachectl -k start > /dev/null 2>&1
+
+	echo -e "=== Apache server restarted ... \n"
+	echo -e "=== Virtual Host & Server configuration - Finished successfully \n"
+
+	echo -e "=== Installing WordPress ..."
+	echo -e "=== Downloading latest WordPress and extracting files."
+	
+	{
+		echo 'htdocs/wordpress'
+		echo 'htdocs/content/plugins'
+		echo 'htdocs/content/uploads'
+		echo 'htdocs/content/upgrade'
+	} > .gitignore
+	chmod 755 .gitignore
+
+	{
+		echo "<?php"
+		echo "define('DB_NAME', '"$site_db"');"
+		echo "define('DB_USER', '"$site_db_user"');"
+		echo "define('DB_PASSWORD', '"$DEFAULT_MYSQL_USER_PASS"');"
+		echo "define('DB_HOST', '"$MYSQL_HOST"');"
+		echo "define('DB_CHARSET', 'utf8');"
+		echo ""
+		echo "define('WP_DEBUG', true);"
+		echo ""
+		echo "define('EMPTY_TRASH_DAYS', 5 );"
+		echo ""
+		echo "define('WP_POST_REVISIONS', 10);"
+		echo "define('WP_HOME', 'http://"$1"');"
+		echo "define('WP_SITEURL', 'http://"$1"/wordpress');"
+		echo "define('WP_CONTENT_DIR', '"$APACHE_VHOSTS_ROOT_DIR$1"/htdocs/content');"
+		echo "define('WP_CONTENT_URL', 'http://"$1"/content');"
+	} > config/env/development.php
+	chmod 755 config/env/development.php
+
+	{
+		echo "<?php"
+		echo "define('DB_NAME', '"$site_db"');"
+		echo "define('DB_USER', '"$site_db_user"');"
+		echo "define('DB_PASSWORD', '"$DEFAULT_MYSQL_USER_PASS"');"
+		echo "define('DB_HOST', '"$MYSQL_HOST"');"
+		echo "define('DB_CHARSET', 'utf8');"
+		echo ""
+		echo "define('WP_DEBUG', false);"
+		echo ""
+		echo "define('EMPTY_TRASH_DAYS', 30 );  // 30 days"
+		echo "define('DISALLOW_FILE_MODS',true); // Disable Plugin and Theme Update and Installation"
+		echo ""
+		echo "define('WP_POST_REVISIONS', 20); // Specify the Number of Post Revisions"
+		echo "define('WP_HOME', 'http://"$1".test.rhyndo.com');"
+		echo "define('WP_SITEURL', 'http://"$1".test.rhyndo.com/wordpress');"
+		echo "define('WP_CONTENT_DIR', '"$APACHE_VHOSTS_ROOT_DIR$1"/htdocs/content');"
+		echo "define('WP_CONTENT_URL', 'http://"$1".test.rhyndo.com/content');"
+	} > config/env/staging.php
+	chmod 755 config/env/staging.php
+
+	{
+		echo "<?php"
+		echo "define('DB_NAME', '"$site_db"');"
+		echo "define('DB_USER', '"$site_db_user"');"
+		echo "define('DB_PASSWORD', '"$DEFAULT_MYSQL_USER_PASS"');"
+		echo "define('DB_HOST', '"$MYSQL_HOST"');"
+		echo "define('DB_CHARSET', 'utf8');"
+		echo ""
+		echo "define('WP_DEBUG', false);"
+		echo ""
+		echo "define('EMPTY_TRASH_DAYS', 30 );  // 30 days"
+		echo "define('DISALLOW_FILE_MODS',true); // Disable Plugin and Theme Update and Installation"
+		echo ""
+		echo "define('WP_POST_REVISIONS', 20); // Specify the Number of Post Revisions"
+		echo "define('WP_HOME', 'http://"$1".test.rhyndo.com');"
+		echo "define('WP_SITEURL', 'http://"$1".test.rhyndo.com/wordpress');"
+		echo "define('WP_CONTENT_DIR', '"$APACHE_VHOSTS_ROOT_DIR$1"/htdocs/content');"
+		echo "define('WP_CONTENT_URL', 'http://"$1".test.rhyndo.com/content');"
+	} > config/env/live.php
+	chmod 755 config/env/live.php
+	cd htdocs
+
+	{
+		echo "path: wordpress"
+		echo "color: true"
+	} > wp-cli.local.yml
+	chmod 755 wp-cli.local.yml
+
+	# Download latest stable WordPress release
+	cd wordpress
+	wp core download | grep 'Success' > /dev/null 2>&1
+	if [ $? != 0 ]
+	then
+		exit 1
+	fi
+	cd ..
+
+	# Move wp-content outside and rename it
+	mv wordpress/wp-content content
+	rm content/themes/twentytwelve
+
+	# Create media storage folder and set appropriate permissions
+	mkdir content/uploads
+	chmod 777 content/uploads
+
+	# Create wp-config
+	{
+		echo "<?php"
+		echo "define('APP_ROOT', dirname(__DIR__));"
+		echo "define('APP_ENV', getenv('APPLICATION_ENV'));"
+		echo ""
+		echo "define('WPLANG', '');"
+		echo ""
+		echo "if (file_exists(APP_ROOT . 'config/env/local.php')) {"
+		echo "	require APP_ROOT . 'config/env/local.php';"
+		echo "} else {"
+		echo "	require APP_ROOT . 'config/env/' . APP_ENV . '.php';"
+		echo "}"
+		echo ""
+		echo '$table_prefix  = "wp_";'
+		echo "if ( !defined('ABSPATH') )"
+		echo "	define('ABSPATH', dirname(__FILE__) . '/');"
+		echo "	require_once(ABSPATH . 'wp-settings.php');"
+	} > wp-config.php
+	chmod 755 wp-config.php
+
+	# Create additional index.php file outside the WordPress folder
+	{
+		echo "<?php"
+		echo "define('WP_USE_THEMES', true);"
+		echo "require('./wordpress/wp-blog-header.php');"
+		echo "?>"
+	} > index.php
+	chmod 755 index.php
+
+	# Create DB and add privileges
+	mysqladmin -u $MYSQL_ROOT_USER -p"$MYSQL_ROOT_PASS" create $site_db > /dev/null 2>&1
+	{ 
+		echo "use mysql;"
+		echo grant all on ${site_db}.* to "$site_db_user"@'localhost' identified by "'${DEFAULT_MYSQL_USER_PASS}';"
+		echo "flush privileges;"
+	} > $APACHE_VHOSTS_ROOT_DIR$1/sql.$$
+	mysql -u $MYSQL_ROOT_USER -p"$MYSQL_ROOT_PASS" $site_db < $APACHE_VHOSTS_ROOT_DIR$1/sql.$$ > /dev/null 2>&1
+
+	# Remove the DB & DB User generation file
+	rm $APACHE_VHOSTS_ROOT_DIR$1/sql.$$
+	echo -e "=== Database created successfully"
+
+	# Install WordPress database tables and an admin account
+	wp core install --url=$APACHE_VHOSTS_ROOT_DIR$1/htdocs/wordpress --title=$1 --admin_name=$DEFAULT_WORDPRESS_USER_NAME --admin_email=$DEFAULT_WORDPRESS_USER_EMAIL --admin_password=$DEFAULT_WORDPRESS_USER_PASS > /dev/null 2>&1
+
+	echo -e "=== Custom WordPress configuration finished \n"
+
+	# Backup local DB 
+	db_backup_path=$APACHE_VHOSTS_ROOT_DIR$1/database
+
+	# Get the date so that it can be used as part of the filename created
+	now=`date +"%m_%d_%Y_%T"`
+
+	wp db export $db_backup_path/$1_$now.init.sql > /dev/null 2>&1
+	chmod 755 $db_backup_path/$1_$now.init.sql
+	echo -e "=== Database backup created \n"
+
+	#setup git deployment
+	cd ..
+	git init > /dev/null 2>&1
+	git remote add staging ssh://$1@$server/home/$1/repo/$1.git > /dev/null 2>&1
+	git add . > /dev/null 2>&1
+	git commit -am "Initial commit"  > /dev/null 2>&1
+	git push staging master > /dev/null 2>&1
+
+	echo -e "=== Git repo created & remote added \n"
+	
+	# get back to the initial directory
+	cd /${cwd}
+
+	echo -e "=== DONE! WordPress installation & configuration - Finished! \n"
+
+	#if [ $USE_CONSULAR = 1 ]
+	#then
+		#lazyconsular-installproject $1
+	#fi
+
+	echo -e "=== Installing database ... \n"
+	
+	echo -e "=== Opening sites in the default browser ... \n"
 
 	open 'http://'$1'/'
 	open 'http://'$1'/wordpress/wp-admin'
 
+	open 'http://'$1'.test.rhyndo.com/'
+	open 'http://'$1'.test.rhyndo.com/wordpress/wp-admin'
+
 	echo -e "==============================================================================="
 	echo -e "=== WordPress installation and configuration finished successfully  ==========="
 	echo -e "==============================================================================="
-	echo -e "=== Local installation - VHost file - $APACHE_VHOSTS_CONF_DIR$1"
-	echo -e "=== Local installation - Site root - $APACHE_VHOSTS_ROOT_DIR$1"
-	echo -e "=== Local installation - wp.config.php - $APACHE_VHOSTS_ROOT_DIR$1/wp-config.php"
-	echo -e "=== Local installation - Address - http://$1/"
-	echo -e "=== Local installation - WP-ADMIN - http://$1/wordpress/wp-admin"
+	echo -e "=== Development env - VHost file - $APACHE_VHOSTS_CONF_DIR$1"
+	echo -e "=== Development env - Site root - $APACHE_VHOSTS_ROOT_DIR$1"
+	echo -e "=== Development env - wp.config.php - $APACHE_VHOSTS_ROOT_DIR$1/wp-config.php"
+	echo -e "=== Development env - Address - http://$1/"
+	echo -e "=== Development env - WP-ADMIN - http://$1/wordpress/wp-admin"
+	echo -e "==============================================================================="
+	echo -e "=== Staging env - Address - http://$1.test.rhyndo.com/"
+	echo -e "=== Staging env - WP-ADMIN - http://$1.test.rhyndo.com/wordpress/wp-admin"
 	echo -e "=============================================================================== \n"
