Various improvements to the checks made before installation starts
Using wp-cli for downloading latest version of WordPress

Checking for wp-cli before installation starts

More cross-platform check for is mysql running

Added two new variables to for Hosts file and Consular usage

diff --git a/lazyvhost-create b/lazyvhost-create
--- a/lazyvhost-create
+++ b/lazyvhost-create
@@ -1,41 +1,50 @@
 #!/bin/bash
 
-if [ -z "$1" ] # Is parameter 1 zero length?
-then
-	echo -e "Error: crete_vhost requires a site name to be specified."
-else
-	if [ -d "$APACHE_VHOSTS_ROOT_DIR$1" ] # Does the new VHost directory already exists?
+	MSG_INSTALL_ABORTED="Installation aborted."
+
+	echo -e "==============================================================================="
+	echo -e "=== LazyVHost Create - Fast and easy VHost management = = = = = ==============="
+	echo -e "==============================================================================="
+
+	# Is parameter 1 zero length?
+	if [ -z "$1" ]
+	then
+		echo -e "ERROR: Requires one attribute."
+		echo -e "=== ${MSG_INSTALL_ABORTED} ===================================================== \n"
+		exit 1
+	fi
+
+	# Does the new VHost directory already exists?
+	if [ -d "$APACHE_VHOSTS_ROOT_DIR$1" ] 
 	then 
-		echo -e 'Error: Site directory already exists! Cannot create new VHost. \n'
-	else	
-		echo -e "\nVirtual Host & Server configuration ...\n"
+		echo -e '=== ERROR: Site directory already exists! Cannot create new VHost. \n'
+		echo -e "=== ${MSG_INSTALL_ABORTED} ===================================================== \n"
+		exit 1
+	fi
 
-		mkdir $APACHE_VHOSTS_ROOT_DIR$1
-		
-		#echo '127.0.0.1	'$1 | sudo tee -a /etc/hosts
-		
-		sudo sh -c "echo '127.0.0.1	'$1 >> /etc/hosts" # Add the site to the local hosts file
+	mkdir $APACHE_VHOSTS_ROOT_DIR$1
 
-		echo -e "--- hosts file updated."
+	{ # Create the VHost file
+		echo '<VirtualHost *:80>'
+		echo '	DocumentRoot "'$APACHE_VHOSTS_ROOT_DIR$1'"'
+		echo '	ServerName '$1
+		echo '	<Directory '$APACHE_VHOSTS_ROOT_DIR$1'>'
+		echo '		Options FollowSymLinks'
+		echo '		AllowOverride All'
+		echo '		Order deny,allow'
+		echo '		Allow from all'
+		echo '	</Directory>'
+		echo '</VirtualHost>'
+	} > $APACHE_VHOSTS_ROOT_DIR$1.conf
 
-		{ # Create the VHost file
-			echo '<VirtualHost *:80>'
-			echo '	DocumentRoot "'$APACHE_VHOSTS_ROOT_DIR$1'"'
-			echo '	ServerName '$1
-			echo '	<Directory '$APACHE_VHOSTS_ROOT_DIR$1'>'
-			echo '		Options FollowSymLinks'
-			echo '		AllowOverride All'
-			echo '		Order deny,allow'
-			echo '		Allow from all'
-			echo '	</Directory>'
-			echo '</VirtualHost>'
-		} > $APACHE_VHOSTS_ROOT_DIR$1.conf
-		sudo mv $APACHE_VHOSTS_ROOT_DIR$1.conf $APACHE_VHOSTS_CONF_DIR
-		echo -e "--- vhost file created."
+	sudo mv $APACHE_VHOSTS_ROOT_DIR$1.conf $APACHE_VHOSTS_CONF_DIR
 
-		sudo apachectl graceful # ! Warning - this is OS X specific
-		echo -e "--- Apache restarted.\n"
-		
-		echo -e "Virtual Host & Server configuration - Finished! \n"
-	fi	
-fi
+	echo -e "=== VHost file created"
+
+	# Add the site to the local hosts file
+	sudo sh -c "echo '127.0.0.1	'$1 >> $HOSTS_FILE"
+
+	echo -e "=== hosts file updated"
+	echo -e "=== Restarting Apache server ... \n"
+	sudo apachectl graceful # ! Warning - this is OS X specific
+	echo -e "=== Virtual Host & Server configuration - Finished successfully \n"
diff --git a/lazywp-install b/lazywp-install
--- a/lazywp-install
+++ b/lazywp-install
@@ -1,121 +1,153 @@
 #!/bin/bash
 
-if [ -z "$1" ] # Is parameter #1 zero length?
-then
-	echo -e "\n Error: requires site name to be specified. \n"
-else
+	MSG_INSTALL_ABORTED="Installation aborted."
 
-	site_db=$1			# Name of the MySQL wordpress database
-	site_db_user=$1		# Database user account
+	echo -e "==============================================================================="
+	echo -e "=== LazyWP Install - WordPress install for lazy developers = = = =============="
+	echo -e "=============================================================================== \n"
+
+	if [ -z "$1" ] # Is parameter #1 zero length?
+	then
+		echo -e "=== ERROR: Requires one argument. Site name has to be specified."
+		echo -e "=== e.g: lazywp-install mysite \n"
+		echo -e "=== ${MSG_INSTALL_ABORTED} ===================================================== \n"
+		exit 1
+	fi
+
+	site_db=$1		# Name of the MySQL wordpress database
+	site_db_user=$1	# Database user account
+	cwd=${PWD#*/}
+
+	hash wp &> /dev/null
+	if [ $? -eq 1 ]; then
+		echo >&2 "=== ERROR: wp-cli is required. Check http://wp-cli.org for more information."
+		echo -e "\n=== Just execute the following command in your terminal: \n"
+		echo -e "    curl https://raw.github.com/wp-cli/wp-cli.github.com/master/installer.sh | bash \n"
+		echo -e "    (Make sure to read the instructions) \n"
+		echo -e "=== ${MSG_INSTALL_ABORTED} ===================================================== \n"
+		exit 1
+	fi
+
+	UP=$(pgrep mysql | wc -l);
+	if [ "$UP" -ne 1 ];
+	then
+		echo -e "=== ERROR: MySQL not running!\n"
+		echo -e "=== This script needs MySQL running in order to install and configure"
+		echo -e "=== the WordPress database. \n"
+		echo -e "=== ${MSG_INSTALL_ABORTED} ===================================================== \n"
+		exit 1
+	fi
 
 	if [ -d $MYSQL_DATA_DIR$site_db ]
 	then
-		echo -e "Error: Database $site_db aready exists! Wordpress installation aborted! \n"
-	else
-		mysql.server status | grep 'SUCCESS' > /dev/null 2>&1
-		if [ $? != 0 ]
-		then
-			echo -e 'Error: MySQL not running'
-		else
-
-			cwd=${PWD#*/}
-
-			lazyvhost-create $1
-			
-			echo -e "Installing WordPress ...\n"
-
-			echo -e '--- MySQL server check passed: running'
-
-			cp ${APACHE_VHOSTS_ROOT_DIR}latest.tar.gz $APACHE_VHOSTS_ROOT_DIR$1
-			cd $APACHE_VHOSTS_ROOT_DIR$1
-			wget http://wordpress.org/latest.tar.gz
-
-			if [ ! -f $APACHE_VHOSTS_ROOT_DIR$1/latest.tar.gz ]; then
-			    echo "Error: WordPress download failed!"
-				exit 0
-			fi
-
-			tar xzf $APACHE_VHOSTS_ROOT_DIR$1/latest.tar.gz > /dev/null 2>&1 && 
-			rm $APACHE_VHOSTS_ROOT_DIR$1/latest.tar.gz
-			echo -e "--- getting the latest WordPress and extracting files."
-
-			mv $APACHE_VHOSTS_ROOT_DIR$1/wordpress/wp-content $APACHE_VHOSTS_ROOT_DIR$1/content
-			echo -e "--- wp-content folder moved outside WordPress folder."
-
-			# Create wp-config
-			{
-				echo "<?php"
-				echo "define('DB_NAME', '"$site_db"');"
-				echo "define('DB_USER', '"$site_db_user"');"
-				echo "define('DB_PASSWORD', '"$DEFAULT_MYSQL_USER_PASS"');"
-				echo "define('DB_HOST', '"$MYSQL_HOST"');"
-				echo "define('DB_CHARSET', 'utf8');"
-				echo "define('EMPTY_TRASH_DAYS', 30 );  // 30 days"
-				echo "define('DISALLOW_FILE_MODS',true); // Disable Plugin and Theme Update and Installation"
-				echo "define('WP_POST_REVISIONS', 20); // Specify the Number of Post Revisions"
-				echo "define('WP_HOME', 'http://"$1"');"
-				echo "define('WP_SITEURL', 'http://"$1"/wordpress');"
-				echo "define('WP_CONTENT_DIR', '"$APACHE_VHOSTS_ROOT_DIR$1"/content');"
-				echo "define('WP_CONTENT_URL', 'http://"$1"/content');"
-				echo '$table_prefix  = "wp_";'
-				echo "define('WPLANG', '');"
-				echo "define('WP_DEBUG', false);"
-				echo "if ( !defined('ABSPATH') )"
-				echo "	define('ABSPATH', dirname(__FILE__) . '/');"
-				echo "	require_once(ABSPATH . 'wp-settings.php');"
-			} > $APACHE_VHOSTS_ROOT_DIR$1/wordpress/wp-config.php
-			echo -e "--- wp-config created."
-			
-			# Create additional index.php file outside the WordPress folder
-			{
-				echo "<?php"
-				echo "define('WP_USE_THEMES', true);"
-				echo "require('./wordpress/wp-blog-header.php');"
-				echo "?>"
-			} > $APACHE_VHOSTS_ROOT_DIR$1/index.php
-			echo -e "--- index.php file created."
-			
-			# Create DB and add privileges
-			mysqladmin -u $MYSQL_ROOT_USER -p"$MYSQL_ROOT_PASS" create $site_db > /dev/null 2>&1
-			{ 
-				echo "use mysql;"
-				echo grant all on ${site_db}.* to "$site_db_user"@'localhost' identified by "'${DEFAULT_MYSQL_USER_PASS}';"
-				echo "flush privileges;"
-			} > $APACHE_VHOSTS_ROOT_DIR$1/sql.$$
-			mysql -u $MYSQL_ROOT_USER -p"$MYSQL_ROOT_PASS" $site_db < $APACHE_VHOSTS_ROOT_DIR$1/sql.$$ > /dev/null 2>&1
-			echo -e "--- database & user created."
-			
-			# remove the database & user generation file
-			rm $APACHE_VHOSTS_ROOT_DIR$1/sql.$$
-
-			# creation of a bare-bones development theme
-			cd $APACHE_VHOSTS_ROOT_DIR$1/content/themes
-			cp $APACHE_VHOSTS_ROOT_DIR/wp_theme_template.zip .
-			tar xf wp_theme_template.zip > /dev/null 2>&1 &&
-			mv wp_theme_template $1
-
-			# cleanup the zip
-			rm wp_theme_template.zip
-
-			# go into core and install db and activate the new theme
-			cd $APACHE_VHOSTS_ROOT_DIR$1/wordpress
-			wp core install --url=$APACHE_VHOSTS_ROOT_DIR$1/wordpress --title=$1 --admin_name=$DEFAULT_WORDPRESS_USER_NAME --admin_email=$DEFAULT_WORDPRESS_USER_EMAIL --admin_password=$DEFAULT_WORDPRESS_USER_PASS > /dev/null 2>&1
-			echo -e "--- WordPress database install & admin user created."
-			wp theme activate "$1" > /dev/null 2>&1
-			echo -e "--- default development theme created and activated. \n"
-
-			# get back to the initial directory
-			cd /${cwd}
-			
-			echo -e "WordPress installation & configuration - Finished! \n"
-			
-			lazyconsular-installproject $1
-			echo -e "Consular project created. \n"
-
-			echo -e "Opening site in the default browser. \n"
-			open 'http://'$1'/'
-			open 'http://'$1'/wordpress/wp-admin'
-
-		fi
+		echo -e "=== ERROR: Database '$site_db' aready exists! \n"
+		echo -e "=== ${MSG_INSTALL_ABORTED} ===================================================== \n"
+		exit 1
 	fi
-fi
+
+	./lazyvhost-create $1
+
+	echo -e "=== Installing WordPress ..."
+	echo -e "=== Downloading latest WordPress and extracting files."
+
+	cd $APACHE_VHOSTS_ROOT_DIR$1
+	mkdir wordpress
+	cd wordpress
+
+	wp core download | grep 'Success' > /dev/null 2>&1
+	if [ $? != 0 ]
+	then
+		exit 1
+	fi
+
+	cd ..
+	mv $APACHE_VHOSTS_ROOT_DIR$1/wordpress/wp-content $APACHE_VHOSTS_ROOT_DIR$1/content
+
+	# Create wp-config
+	{
+		echo "<?php"
+		echo "define('DB_NAME', '"$site_db"');"
+		echo "define('DB_USER', '"$site_db_user"');"
+		echo "define('DB_PASSWORD', '"$DEFAULT_MYSQL_USER_PASS"');"
+		echo "define('DB_HOST', '"$MYSQL_HOST"');"
+		echo "define('DB_CHARSET', 'utf8');"
+		echo "define('EMPTY_TRASH_DAYS', 30 );  // 30 days"
+		echo "define('DISALLOW_FILE_MODS',true); // Disable Plugin and Theme Update and Installation"
+		echo "define('WP_POST_REVISIONS', 20); // Specify the Number of Post Revisions"
+		echo "define('WP_HOME', 'http://"$1"');"
+		echo "define('WP_SITEURL', 'http://"$1"/wordpress');"
+		echo "define('WP_CONTENT_DIR', '"$APACHE_VHOSTS_ROOT_DIR$1"/content');"
+		echo "define('WP_CONTENT_URL', 'http://"$1"/content');"
+		echo '$table_prefix  = "wp_";'
+		echo "define('WPLANG', '');"
+		echo "define('WP_DEBUG', false);"
+		echo "if ( !defined('ABSPATH') )"
+		echo "	define('ABSPATH', dirname(__FILE__) . '/');"
+		echo "	require_once(ABSPATH . 'wp-settings.php');"
+	} > $APACHE_VHOSTS_ROOT_DIR$1/wp-config.php
+
+	# Create additional index.php file outside the WordPress folder
+	{
+		echo "<?php"
+		echo "define('WP_USE_THEMES', true);"
+		echo "require('./wordpress/wp-blog-header.php');"
+		echo "?>"
+	} > $APACHE_VHOSTS_ROOT_DIR$1/index.php
+
+	# Create DB and add privileges
+	mysqladmin -u $MYSQL_ROOT_USER -p"$MYSQL_ROOT_PASS" create $site_db > /dev/null 2>&1
+
+	{ 
+		echo "use mysql;"
+		echo grant all on ${site_db}.* to "$site_db_user"@'localhost' identified by "'${DEFAULT_MYSQL_USER_PASS}';"
+		echo "flush privileges;"
+	} > $APACHE_VHOSTS_ROOT_DIR$1/sql.$$
+
+	mysql -u $MYSQL_ROOT_USER -p"$MYSQL_ROOT_PASS" $site_db < $APACHE_VHOSTS_ROOT_DIR$1/sql.$$ > /dev/null 2>&1
+
+	echo -e "=== Database created successfully"
+
+	# Remove the DB & DB User generation file
+	rm $APACHE_VHOSTS_ROOT_DIR$1/sql.$$
+
+	# Go to wordpress folder and install WordPress database and the Admin account
+	cd $APACHE_VHOSTS_ROOT_DIR$1/wordpress
+	wp core install --url=$APACHE_VHOSTS_ROOT_DIR$1/wordpress --title=$1 --admin_name=$DEFAULT_WORDPRESS_USER_NAME --admin_email=$DEFAULT_WORDPRESS_USER_EMAIL --admin_password=$DEFAULT_WORDPRESS_USER_PASS > /dev/null 2>&1
+
+	echo -e "=== Custom WordPress configuration finished"
+
+	#creation of a bare-bones development theme
+	#cd $APACHE_VHOSTS_ROOT_DIR$1/content/themes
+	#cp $APACHE_VHOSTS_ROOT_DIR/wp_theme_template.zip .
+	#tar xf wp_theme_template.zip > /dev/null 2>&1 &&
+	#mv wp_theme_template $1
+
+	# cleanup the zip
+	#rm wp_theme_template.zip
+
+	#wp theme activate "$1" > /dev/null 2>&1
+	#echo -e "--- default development theme created and activated. \n"
+
+	# get back to the initial directory
+	cd /${cwd}
+
+	echo -e "WordPress installation & configuration - Finished! \n"
+
+	if [ $USE_CONSULAR = 1 ]
+	then
+		lazyconsular-installproject $1
+	fi
+
+	echo -e "=== Opening site in the default browser ... \n"
+	open 'http://'$1'/'
+	open 'http://'$1'/wordpress/wp-admin'
+
+	echo -e "==============================================================================="
+	echo -e "=== WordPress installation and configuration finished successfully  ==========="
+	echo -e "==============================================================================="
+	echo -e "=== Local installation - VHost file - $APACHE_VHOSTS_CONF_DIR$1"
+	echo -e "=== Local installation - Site root - $APACHE_VHOSTS_ROOT_DIR$1"
+	echo -e "=== Local installation - wp.config.php - $APACHE_VHOSTS_ROOT_DIR$1/wp-config.php"
+	echo -e "=== Local installation - Address -	http://$1/"
+	echo -e "=== Local installation - WP-ADMIN - http://$1/wordpress/wp-admin"
+	echo -e "=============================================================================== \n"
